export const FINAL_PROJECT_RUBRIC = [
  {
    id: 'story-structure',
    title: 'Story and structure',
    description: 'Clear premise, conflict, resolution, and audience fit.',
    maximumPoints: 20,
    performanceLevels: [
      { label: 'Developing', points: 10 },
      { label: 'Secure', points: 16 },
      { label: 'Strong', points: 20 },
    ],
    orderIndex: 1,
  },
  {
    id: 'character-arc',
    title: 'Character and arc',
    description: 'The protagonist has a clear want, need, obstacle, and change.',
    maximumPoints: 20,
    performanceLevels: [
      { label: 'Developing', points: 10 },
      { label: 'Secure', points: 16 },
      { label: 'Strong', points: 20 },
    ],
    orderIndex: 2,
  },
  {
    id: 'visual-language',
    title: 'Visual language and camera choices',
    description: 'Shot choices, camera angle, lighting, and composition support meaning.',
    maximumPoints: 20,
    performanceLevels: [
      { label: 'Developing', points: 10 },
      { label: 'Secure', points: 16 },
      { label: 'Strong', points: 20 },
    ],
    orderIndex: 3,
  },
  {
    id: 'continuity',
    title: 'Scene continuity and consistency',
    description: 'Characters, wardrobe, setting, and visual style remain coherent.',
    maximumPoints: 15,
    performanceLevels: [
      { label: 'Developing', points: 7 },
      { label: 'Secure', points: 12 },
      { label: 'Strong', points: 15 },
    ],
    orderIndex: 4,
  },
  {
    id: 'pacing-prep',
    title: 'Editing and pacing preparation',
    description: 'The sequence is prepared for assembly with purposeful pacing.',
    maximumPoints: 15,
    performanceLevels: [
      { label: 'Developing', points: 7 },
      { label: 'Secure', points: 12 },
      { label: 'Strong', points: 15 },
    ],
    orderIndex: 5,
  },
  {
    id: 'creative-intention',
    title: 'Presentation and creative intention',
    description: 'The student can explain creative choices and revisions.',
    maximumPoints: 10,
    performanceLevels: [
      { label: 'Developing', points: 5 },
      { label: 'Secure', points: 8 },
      { label: 'Strong', points: 10 },
    ],
    orderIndex: 6,
  },
];

export const FILMMAKING_COURSE_TEMPLATE = {
  title: 'AI Storytelling and Virtual Filmmaking',
  description: 'A four-week workshop where students develop a short film, advert, PSA, or animated story using the Raivstream creative workspace.',
  learningOutcome: 'Each student produces a short film, advert, PSA, or animated story concept with story, character, scene, image, and storybook milestones.',
  audienceDescription: 'Beginners, young creators, educators, and studio teams learning AI-assisted filmmaking.',
  durationWeeks: 4,
  sessionsPerWeek: 2,
  sessionDurationMinutes: 60,
  modules: [
    {
      title: 'Week 1: Story Foundations',
      description: 'Story, theme, conflict, resolution, audience, Story Spark, and Story DNA.',
      lessons: [
        {
          title: 'Session 1: Story, Theme, Conflict, Resolution, Audience',
          summary: 'Build a clear premise and understand what makes a story work for a chosen audience.',
          learningObjectives: ['Identify protagonist, goal, conflict, and resolution', 'Describe the intended audience', 'Write a one-sentence story premise'],
          lessonContent: 'Focus on story clarity before production. A strong project begins with a clear protagonist, goal, obstacle, and emotional promise.',
          estimatedMinutes: 60,
          lessonType: 'CLASSROOM',
        },
        {
          title: 'Session 2: Story Spark and Story DNA',
          summary: 'Use Story Spark to turn an idea into guided questions, story, and Story DNA.',
          learningObjectives: ['Create a Story Workspace project', 'Generate guided questions', 'Review Story DNA for theme and structure'],
          lessonContent: 'Students use Story Spark, answer guided questions, and review the generated Story DNA before revising.',
          estimatedMinutes: 60,
          lessonType: 'WORKSPACE',
        },
      ],
    },
    {
      title: 'Week 2: Characters and Visual Worlds',
      description: 'Character arcs, relationships, visual style, setting, production design, and continuity.',
      lessons: [
        {
          title: 'Session 3: Character Wants, Needs, Flaws, Relationships, and Arcs',
          summary: 'Shape protagonists and supporting characters so visual generations remain narratively consistent.',
          learningObjectives: ['Define want, need, fear, and flaw', 'Map a character arc', 'Edit Character Director cards'],
          lessonContent: 'Character consistency starts with clear emotional and visual memory. Students revise Character Director cards.',
          estimatedMinutes: 60,
          lessonType: 'WORKSPACE',
        },
        {
          title: 'Session 4: Visual Style, Setting, Production Design, and Continuity',
          summary: 'Choose a visual style and production design rules that support the story.',
          learningObjectives: ['Pick a visual style', 'Describe locations and props', 'Protect wardrobe and world continuity'],
          lessonContent: 'Students document the visual world and continuity rules before image generation.',
          estimatedMinutes: 60,
          lessonType: 'LAB',
        },
      ],
    },
    {
      title: 'Week 3: Directing',
      description: 'Shot sizes, camera angles, composition, lighting, mood, movement, and pacing.',
      lessons: [
        {
          title: 'Session 5: Shot Sizes, Camera Angles, Composition, and Visual Meaning',
          summary: 'Use camera decisions to communicate emotion and story information.',
          learningObjectives: ['Choose shot size intentionally', 'Explain camera angle choices', 'Apply composition for clarity'],
          lessonContent: 'Students choose camera settings for scenes and explain why those choices fit the story.',
          estimatedMinutes: 60,
          lessonType: 'CLASSROOM',
        },
        {
          title: 'Session 6: Scene Direction, Lighting, Mood, Movement, and Pacing',
          summary: 'Direct each scene using lighting, emotion, time of day, and pacing controls.',
          learningObjectives: ['Edit Scene Director settings', 'Create mood continuity', 'Prepare scenes for image generation'],
          lessonContent: 'Students use Scene Director to refine mood, lighting, camera style, and pacing.',
          estimatedMinutes: 60,
          lessonType: 'WORKSPACE',
        },
      ],
    },
    {
      title: 'Week 4: Production',
      description: 'Asset generation, review, selection, revision, final assembly preparation, and critique.',
      lessons: [
        {
          title: 'Session 7: Asset Generation, Review, Selection, and Revision',
          summary: 'Generate image versions, compare them, favorite strong images, and select active Storybook images.',
          learningObjectives: ['Generate scene images', 'Compare and favorite assets', 'Set active images for Storybook'],
          lessonContent: 'Students use the Asset Manager to preserve image history and choose the best active images.',
          estimatedMinutes: 60,
          lessonType: 'LAB',
        },
        {
          title: 'Session 8: Final Assembly Preparation, Presentation, Critique, and Showcase',
          summary: 'Prepare the project for future movie assembly and present creative intention.',
          learningObjectives: ['Review storybook flow', 'Prepare critique notes', 'Reflect on revisions'],
          lessonContent: 'Students present the Storybook and explain how story, character, scenes, and visual choices evolved.',
          estimatedMinutes: 60,
          lessonType: 'CRITIQUE',
        },
      ],
    },
  ],
  assignments: [
    {
      title: 'Assignment 1: One-Sentence Story',
      brief: 'Submit a clear one-sentence story premise.',
      instructions: 'Include premise, protagonist, goal, conflict, and intended audience.',
      deliverableType: 'STORY_IDEA',
      requiredWorkspaceStage: 'STORY_IDEA',
      maximumScore: 100,
      rubric: [
        { id: 'premise', title: 'Premise clarity', maximumPoints: 35, description: 'The story idea is clear and specific.', orderIndex: 1 },
        { id: 'conflict', title: 'Conflict', maximumPoints: 35, description: 'The goal and obstacle are understandable.', orderIndex: 2 },
        { id: 'audience', title: 'Audience fit', maximumPoints: 30, description: 'The intended audience is named and appropriate.', orderIndex: 3 },
      ],
    },
    {
      title: 'Assignment 2: Character Arc',
      brief: 'Link a Story Workspace project and submit the protagonist arc.',
      instructions: 'Submit hero, want, need, fear, flaw, beginning state, and ending state.',
      deliverableType: 'CHARACTER_PROFILE',
      requiredWorkspaceStage: 'CHARACTER_DIRECTOR',
      maximumScore: 100,
      rubric: [
        { id: 'hero', title: 'Hero clarity', maximumPoints: 25, description: 'The hero is visually and emotionally clear.', orderIndex: 1 },
        { id: 'arc', title: 'Arc', maximumPoints: 50, description: 'The beginning and ending states show meaningful change.', orderIndex: 2 },
        { id: 'relationships', title: 'Relationships', maximumPoints: 25, description: 'Relationships support the character arc.', orderIndex: 3 },
      ],
    },
    {
      title: 'Assignment 3: Visual Scene Direction',
      brief: 'Select one scene and explain the scene direction choices.',
      instructions: 'Explain shot size, camera angle, lighting, emotion, and the reason for each choice.',
      deliverableType: 'SCENE_PLAN',
      requiredWorkspaceStage: 'SCENE_DIRECTOR',
      maximumScore: 100,
      rubric: [
        { id: 'camera', title: 'Camera choice', maximumPoints: 35, description: 'Camera choices support story meaning.', orderIndex: 1 },
        { id: 'lighting', title: 'Lighting and mood', maximumPoints: 35, description: 'Lighting and mood match the scene purpose.', orderIndex: 2 },
        { id: 'reasoning', title: 'Creative reasoning', maximumPoints: 30, description: 'The explanation connects choices to audience impact.', orderIndex: 3 },
      ],
    },
    {
      title: 'Assignment 4: Final Project',
      brief: 'Submit the final Story Workspace project and creative statement.',
      instructions: 'Submit the Story Workspace project, final Storybook or future video plan, a short creative statement, and reflection on revisions.',
      deliverableType: 'STORYBOOK',
      requiredWorkspaceStage: 'STORYBOOK',
      maximumScore: 100,
      rubric: FINAL_PROJECT_RUBRIC,
    },
  ],
};
